// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ButtonInfo: typeof import('./src/components/button/info/src/ButtonInfo.vue')['default']
    ButtonInfoExample: typeof import('./src/components/button/info/examples/ButtonInfoExample.vue')['default']
    IFluentCheckboxChecked16Regular: typeof import('~icons/fluent/checkbox-checked16-regular')['default']
    IFluentInfo24Regular: typeof import('~icons/fluent/info24-regular')['default']
    InputCnpj: typeof import('./src/components/input/cnpj/src/InputCnpj.vue')['default']
    InputCnpjExample: typeof import('./src/components/input/cnpj/examples/InputCnpjExample.vue')['default']
    InputCpf: typeof import('./src/components/input/cpf/src/InputCpf.vue')['default']
    InputCpfExample: typeof import('./src/components/input/cpf/examples/InputCpfExample.vue')['default']
    InputMail: typeof import('./src/components/input/mail/src/InputMail.vue')['default']
    InputMailExample: typeof import('./src/components/input/mail/examples/InputMailExample.vue')['default']
    InputText: typeof import('./src/components/input/text/src/InputText.vue')['default']
    InputTextExample: typeof import('./src/components/input/text/examples/InputTextExample.vue')['default']
    NInput: typeof import('naive-ui')['NInput']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
  }
}

export {}
