version: '3.2'
services:
    nodejs:
      image: "node:16"
      user: "node"
      ports:
        - '3000:3000'
      working_dir: /home/node/app
      environment:
        - NODE_ENV=development
      volumes:
        - ./:/home/node/app
      expose:
        - "3000"
      command: "npm run dev"
